#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
npx --no-install commitlint --edit ""
npx --no-install commitlint --edit ""
npx --no-install commitlint --edit ""
npx --no-install commitlint --edit ""
npx commitlint --edit ""
npx commitlint --edit ""
npx commitlint --edit
npx commitlint --edit
npx --no-install commitlint --edit $1